-- ============================================================
-- Migration 018: create_employee_full RPC
-- Creates a new auth user + profile + reporting record in one
-- atomic transaction. Called by the Add Employee form.
-- ============================================================

CREATE OR REPLACE FUNCTION public.create_employee_full(
  p_name          TEXT,
  p_email         TEXT,
  p_phone_no      TEXT     DEFAULT NULL,
  p_department    TEXT     DEFAULT NULL,
  p_role          TEXT     DEFAULT 'Executive',
  p_branch        TEXT     DEFAULT NULL,
  p_reporting_to_id UUID   DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id   UUID;
  v_pass      TEXT;
BEGIN
  v_pass := COALESCE(NULLIF(TRIM(p_phone_no), ''), 'ChangeMe123!');

  -- 1. Create the auth user via Supabase admin helpers
  --    (SECURITY DEFINER means this runs as the DB owner who has access to auth.users)
  INSERT INTO auth.users (
    id,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    role,
    aud
  )
  VALUES (
    gen_random_uuid(),
    p_email,
    -- bcrypt hash of the password (which is the phone number or ChangeMe123!)
    crypt(v_pass, gen_salt('bf')),
    NOW(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('full_name', p_name),
    NOW(),
    NOW(),
    'authenticated',
    'authenticated'
  )
  RETURNING id INTO v_user_id;

  -- 2. Insert profile row (employee_code auto-generated by column default)
  INSERT INTO profiles (
    id,
    email,
    full_name,
    phone_no,
    role
  ) VALUES (
    v_user_id,
    p_email,
    p_name,
    p_phone_no,
    -- map reporting role text to user_role enum; default to 'executive'
    CASE p_role
      WHEN 'MD'       THEN 'managing_director'
      WHEN 'Director' THEN 'director'
      WHEN 'EA'       THEN 'executive_assistant'
      WHEN 'HR'       THEN 'hr'
      WHEN 'Manager'  THEN 'manager'
      ELSE                 'executive'
    END::user_role
  );

  -- 3. Insert reporting record if any reporting fields provided
  IF p_department IS NOT NULL OR p_branch IS NOT NULL THEN
    INSERT INTO reporting (
      employee_id,
      department,
      role,
      branch,
      reporting_to_id
    ) VALUES (
      v_user_id,
      COALESCE(p_department, ''),
      COALESCE(p_role, 'Executive'),
      COALESCE(p_branch, ''),
      p_reporting_to_id
    );
  END IF;

  RETURN v_user_id;
END;
$$;

-- Grant execute to authenticated users
-- (the component's own RBAC guard controls who can reach this)
GRANT EXECUTE ON FUNCTION public.create_employee_full(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, UUID
) TO authenticated;
