-- ============================================================================
-- Baseline reconciliation migration.
--
-- WHY THIS FILE EXISTS: this project's live Supabase database was built up
-- through a migration history that does NOT match the files in this
-- directory (many objects were created/altered directly, or through
-- migration files that were later renamed/replaced without being kept here).
-- Replaying 001-043 from scratch against a fresh database does not produce
-- today's actual live schema.
--
-- This migration is a point-in-time reconciliation, generated by directly
-- introspecting the live database (tables, columns, enums, constraints, RLS
-- policies, triggers, functions, views) rather than inferring from the
-- other migration files. Every statement is written to be idempotent
-- (IF NOT EXISTS / CREATE OR REPLACE / DROP ... IF EXISTS then CREATE), so:
--   - On the live database this is already applied to: a safe no-op.
--   - On a fresh database that only replayed 001-043: brings it up to
--     parity with what's actually live today.
--
-- This does not attempt to reproduce dead/orphaned objects that exist in
-- the live DB but are no longer wired to anything (e.g. leftover trigger
-- functions from a previous schema iteration with no trigger attached).
-- ============================================================================

-- ── Extensions ──────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- ── Enum types ──────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM (
    'executive', 'manager', 'director', 'managing_director', 'executive_assistant', 'hr'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.job_direction_status AS ENUM (
    'draft', 'active', 'submitted', 'approved', 'rejected', 'completed', 'pending_verification'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TYPE public.job_direction_status ADD VALUE IF NOT EXISTS 'deletion_requested';

DO $$ BEGIN
  CREATE TYPE public.special_task_approval_status AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.notif_type AS ENUM ('info', 'warning', 'danger', 'success');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── Sequences ───────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS public.employee_id_seq START WITH 100 INCREMENT BY 1;

-- ── Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.departments (
  id         uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  name       text UNIQUE NOT NULL,
  head_id    uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id            uuid PRIMARY KEY,
  email         text UNIQUE NOT NULL,
  full_name     text NOT NULL,
  role          public.user_role NOT NULL DEFAULT 'executive',
  department_id uuid,
  manager_id    uuid,
  employee_code text UNIQUE DEFAULT ('EMP-' || lpad(nextval('public.employee_id_seq')::text, 4, '0')),
  phone_no      text UNIQUE,
  branch        text
);
COMMENT ON COLUMN public.profiles.manager_id IS 'Direct supervisor / reporting_to_id for verification chain';
COMMENT ON COLUMN public.profiles.employee_code IS 'HR employee ID (e.g. TW-001)';
COMMENT ON COLUMN public.profiles.phone_no IS 'Contact phone number';
COMMENT ON COLUMN public.profiles.branch IS 'Office / branch location (e.g. Mumbai HQ)';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS department_id uuid;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS manager_id uuid;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS employee_code text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone_no text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS branch text;

CREATE TABLE IF NOT EXISTS public.notifications (
  id         uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  user_id    uuid NOT NULL,
  title      text NOT NULL,
  body       text NOT NULL,
  type       public.notif_type NOT NULL DEFAULT 'info',
  read       boolean NOT NULL DEFAULT false,
  action_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.job_directions (
  id                        text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  work_details              text,
  employee_id               uuid NOT NULL,
  manager_id                uuid NOT NULL,
  department_id             uuid,
  status                    text NOT NULL DEFAULT 'active',
  remarks                   text,
  daily_target              numeric DEFAULT 0,
  weekly_target             numeric DEFAULT 0,
  monthly_target            numeric DEFAULT 0,
  description               text,
  expected_output           text,
  expected_output_achieved  boolean NOT NULL DEFAULT false
);
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS work_details text;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS remarks text;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS expected_output text;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS expected_output_achieved boolean NOT NULL DEFAULT false;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS daily_target numeric DEFAULT 0;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS weekly_target numeric DEFAULT 0;
ALTER TABLE public.job_directions ADD COLUMN IF NOT EXISTS monthly_target numeric DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.job_direction_progress_logs (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_direction_id   text NOT NULL,
  employee_id        uuid NOT NULL,
  amount_completed   numeric NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.special_tasks (
  id               text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  task_name        text NOT NULL,
  remarks          text,
  assigned_by      uuid NOT NULL,
  due_date         date,
  status           text NOT NULL DEFAULT 'Yet to start'
    CHECK (status = ANY (ARRAY['Yet to start','In progress','Completed','In review'])),
  created_at       timestamptz NOT NULL DEFAULT now(),
  approval_status  public.special_task_approval_status NOT NULL DEFAULT 'approved',
  approval_by      uuid,
  approval_at      timestamptz,
  rejection_note   text,
  pending_changes  jsonb,
  completed_at     timestamptz,
  priority         text NOT NULL DEFAULT 'medium'
    CHECK (priority = ANY (ARRAY['low','medium','high','urgent']))
);
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS approval_status public.special_task_approval_status NOT NULL DEFAULT 'approved';
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS approval_by uuid;
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS approval_at timestamptz;
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS rejection_note text;
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS pending_changes jsonb;
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE public.special_tasks ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'medium';

CREATE TABLE IF NOT EXISTS public.task_assignees (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id      text NOT NULL,
  employee_id  uuid NOT NULL,
  assigned_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reporting (
  employee_id      uuid PRIMARY KEY,
  department       text NOT NULL,
  role             text NOT NULL CHECK (role = ANY (ARRAY['MD','Director','EA','Manager','Executive'])),
  branch           text NOT NULL,
  reporting_to_id  uuid
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
  id                          uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  role                        text UNIQUE NOT NULL,
  label                       text NOT NULL,
  can_view_all_branches       boolean NOT NULL DEFAULT false,
  can_view_all_departments    boolean NOT NULL DEFAULT false,
  can_filter_branch           boolean NOT NULL DEFAULT false,
  can_filter_department       boolean NOT NULL DEFAULT false,
  must_be_in_reporting_chain  boolean NOT NULL DEFAULT false,
  updated_at                  timestamptz NOT NULL DEFAULT now(),
  updated_by                  uuid,
  can_create_job_directions   boolean NOT NULL DEFAULT false,
  can_create_tasks            boolean NOT NULL DEFAULT false,
  can_approve_job_directions  boolean NOT NULL DEFAULT false,
  can_approve_tasks           boolean NOT NULL DEFAULT false
);
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_create_job_directions boolean NOT NULL DEFAULT false;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_create_tasks boolean NOT NULL DEFAULT false;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_approve_job_directions boolean NOT NULL DEFAULT false;
ALTER TABLE public.role_permissions ADD COLUMN IF NOT EXISTS can_approve_tasks boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.branches (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code       text UNIQUE NOT NULL,
  name       text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ui_schemas (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name text UNIQUE NOT NULL,
  label      text NOT NULL,
  columns    jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.team_jobs (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title       text NOT NULL,
  description text,
  created_by  uuid NOT NULL,
  head_id     uuid,
  status      text NOT NULL DEFAULT 'active'
    CHECK (status = ANY (ARRAY['active','completed','cancelled'])),
  due_date    date,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.team_job_tasks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id       uuid NOT NULL,
  title        text NOT NULL,
  task_type    text,
  assignee_id  uuid NOT NULL,
  status       text NOT NULL DEFAULT 'Yet to start'
    CHECK (status = ANY (ARRAY['Yet to start','In progress','Completed'])),
  notes        text,
  completed_at timestamptz,
  due_date     date,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.capacity_plans (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch             text NOT NULL,
  department_id      uuid NOT NULL,
  role               text NOT NULL,
  planned_headcount  integer NOT NULL DEFAULT 0,
  plan_month         date NOT NULL,
  created_by         uuid,
  created_at         timestamptz DEFAULT now(),
  updated_at         timestamptz DEFAULT now()
);

-- ── Foreign keys (guarded — ADD CONSTRAINT has no IF NOT EXISTS in Postgres) ──
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_dept_head') THEN
    ALTER TABLE public.departments ADD CONSTRAINT fk_dept_head FOREIGN KEY (head_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_id_fkey') THEN
    ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_manager_id_fkey') THEN
    ALTER TABLE public.profiles ADD CONSTRAINT profiles_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_department_id_fkey') THEN
    ALTER TABLE public.profiles ADD CONSTRAINT profiles_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notifications_user_id_fkey') THEN
    ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_directions_employee_id_fkey') THEN
    ALTER TABLE public.job_directions ADD CONSTRAINT job_directions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_directions_manager_id_fkey') THEN
    ALTER TABLE public.job_directions ADD CONSTRAINT job_directions_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_directions_department_id_fkey') THEN
    ALTER TABLE public.job_directions ADD CONSTRAINT job_directions_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_direction_progress_logs_job_direction_id_fkey') THEN
    ALTER TABLE public.job_direction_progress_logs ADD CONSTRAINT job_direction_progress_logs_job_direction_id_fkey FOREIGN KEY (job_direction_id) REFERENCES public.job_directions(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_direction_progress_logs_employee_id_fkey') THEN
    ALTER TABLE public.job_direction_progress_logs ADD CONSTRAINT job_direction_progress_logs_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'special_tasks_assigned_by_fkey') THEN
    ALTER TABLE public.special_tasks ADD CONSTRAINT special_tasks_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'special_tasks_approval_by_fkey') THEN
    ALTER TABLE public.special_tasks ADD CONSTRAINT special_tasks_approval_by_fkey FOREIGN KEY (approval_by) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_assignees_task_id_fkey') THEN
    ALTER TABLE public.task_assignees ADD CONSTRAINT task_assignees_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.special_tasks(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'task_assignees_employee_id_fkey') THEN
    ALTER TABLE public.task_assignees ADD CONSTRAINT task_assignees_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reporting_employee_id_fkey') THEN
    ALTER TABLE public.reporting ADD CONSTRAINT reporting_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reporting_reporting_to_id_fkey') THEN
    ALTER TABLE public.reporting ADD CONSTRAINT reporting_reporting_to_id_fkey FOREIGN KEY (reporting_to_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'role_permissions_updated_by_fkey') THEN
    ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_jobs_created_by_fkey') THEN
    ALTER TABLE public.team_jobs ADD CONSTRAINT team_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_jobs_head_id_fkey') THEN
    ALTER TABLE public.team_jobs ADD CONSTRAINT team_jobs_head_id_fkey FOREIGN KEY (head_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_job_tasks_job_id_fkey') THEN
    ALTER TABLE public.team_job_tasks ADD CONSTRAINT team_job_tasks_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.team_jobs(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_job_tasks_assignee_id_fkey') THEN
    ALTER TABLE public.team_job_tasks ADD CONSTRAINT team_job_tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.profiles(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'capacity_plans_department_id_fkey') THEN
    ALTER TABLE public.capacity_plans ADD CONSTRAINT capacity_plans_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'capacity_plans_created_by_fkey') THEN
    ALTER TABLE public.capacity_plans ADD CONSTRAINT capacity_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id);
  END IF;
END $$;

-- ── Helper / auth functions ────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.auth_role()
 RETURNS user_role
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT
    CASE WHEN role = 'executive_assistant'
         THEN 'managing_director'::user_role
         ELSE role
    END
  FROM profiles WHERE id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.auth_manager_id()
 RETURNS uuid
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT manager_id FROM profiles WHERE id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.auth_dept_id()
 RETURNS uuid
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT department_id FROM profiles WHERE id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.can_view_employee(p_target_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_caller_id   UUID := auth.uid();
  v_caller_role TEXT;
BEGIN
  SELECT role INTO v_caller_role FROM profiles WHERE id = v_caller_id;

  RETURN CASE
    WHEN v_caller_role IN ('managing_director', 'executive_assistant', 'hr', 'director')
      THEN TRUE
    WHEN v_caller_role = 'manager'
      THEN (p_target_id = v_caller_id OR EXISTS (
        SELECT 1 FROM profiles WHERE id = p_target_id AND manager_id = v_caller_id
      ))
    ELSE
      p_target_id = v_caller_id
  END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_manager_of(target_user_id uuid)
 RETURNS boolean
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM profiles WHERE id = target_user_id AND manager_id = auth.uid()
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_dept_head_of(dept uuid)
 RETURNS boolean
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM departments WHERE id = dept AND head_id = auth.uid()
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_manager_or_above()
 RETURNS boolean
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_role TEXT;
BEGIN
  SELECT role INTO v_role FROM profiles WHERE id = auth.uid();
  RETURN v_role IN ('manager','director','managing_director','executive_assistant','hr');
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_task_assignee(p_task_id text, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM task_assignees
    WHERE task_id = p_task_id AND employee_id = p_user_id
  )
$function$;

CREATE OR REPLACE FUNCTION public.is_task_creator(p_task_id text, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM special_tasks
    WHERE id = p_task_id AND assigned_by = p_user_id
  )
$function$;

CREATE OR REPLACE FUNCTION public.is_team_job_member(p_job_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_uid UUID := auth.uid();
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM team_jobs      WHERE id = p_job_id AND (created_by = v_uid OR head_id = v_uid)
    UNION ALL
    SELECT 1 FROM team_job_tasks WHERE job_id = p_job_id AND assignee_id = v_uid
  );
END;
$function$;

-- ── Trigger functions ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
    COALESCE((NEW.raw_user_meta_data->>'role')::public.user_role, 'executive'::public.user_role)
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$;

CREATE OR REPLACE FUNCTION public.touch_role_permissions_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_reporting_to_profiles_manager()
 RETURNS trigger
 LANGUAGE plpgsql SECURITY DEFINER
AS $function$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    UPDATE public.profiles
    SET manager_id = NEW.reporting_to_id
    WHERE id = NEW.employee_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.profiles
    SET manager_id = NULL
    WHERE id = OLD.employee_id;
  END IF;
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_acknowledge_permission()
 RETURNS trigger
 LANGUAGE plpgsql SECURITY DEFINER
AS $function$
BEGIN
  IF NEW.status = 'acknowledged' AND OLD.status = 'completed' THEN
    IF NEW.assigned_by IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'Only the task creator can acknowledge a completed task';
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_job_direction_updates()
 RETURNS trigger
 LANGUAGE plpgsql SECURITY DEFINER
AS $function$
DECLARE
  v_role text;
BEGIN
  SELECT role::text INTO v_role FROM public.profiles WHERE id = auth.uid();

  -- Only EA, MD, HR, and the manager (OLD.manager_id) can edit job direction details.
  IF NOT (
    OLD.manager_id = auth.uid() OR
    v_role IN ('managing_director', 'executive_assistant', 'hr')
  ) THEN
    IF NEW.work_details IS DISTINCT FROM OLD.work_details OR
       NEW.daily_target IS DISTINCT FROM OLD.daily_target OR
       NEW.weekly_target IS DISTINCT FROM OLD.weekly_target OR
       NEW.monthly_target IS DISTINCT FROM OLD.monthly_target OR
       NEW.remarks IS DISTINCT FROM OLD.remarks THEN
      RAISE EXCEPTION 'Only EA, MD, HR, and their manager are allowed to edit Job Directions details.';
    END IF;
  END IF;

  -- Block non-managers/non-MD/non-EA from directly approving/rejecting/marking active
  IF NOT (
    OLD.manager_id = auth.uid() OR
    v_role IN ('managing_director', 'executive_assistant')
  ) THEN
    IF NEW.status <> OLD.status AND NEW.status IN ('approved', 'rejected', 'active') THEN
      RAISE EXCEPTION 'Only managers, MD, or EA can approve or reject job directions';
    END IF;
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_special_task_updates()
 RETURNS trigger
 LANGUAGE plpgsql SECURITY DEFINER
AS $function$
DECLARE
  v_role text;
BEGIN
  SELECT role::text INTO v_role FROM public.profiles WHERE id = auth.uid();

  IF NOT (
    OLD.assigned_by = auth.uid() OR
    v_role IN ('managing_director', 'executive_assistant')
  ) THEN
    IF NEW.task_name <> OLD.task_name OR
       (NEW.due_date IS DISTINCT FROM OLD.due_date) OR
       (NEW.remarks IS DISTINCT FROM OLD.remarks) THEN
      NEW.approval_status := 'pending';
    END IF;

    IF NEW.approval_status <> OLD.approval_status AND NEW.approval_status IN ('approved', 'rejected') THEN
      RAISE EXCEPTION 'Only managers, MD, or EA can approve or reject tasks';
    END IF;
  END IF;

  RETURN NEW;
END;
$function$;

-- ── Triggers (guarded — CREATE TRIGGER has no IF NOT EXISTS in Postgres) ─────

DROP TRIGGER IF EXISTS trg_enforce_job_direction_updates ON public.job_directions;
CREATE TRIGGER trg_enforce_job_direction_updates
  BEFORE UPDATE ON public.job_directions
  FOR EACH ROW EXECUTE FUNCTION public.enforce_job_direction_updates();

DROP TRIGGER IF EXISTS trg_sync_reporting_to_profiles_manager ON public.reporting;
CREATE TRIGGER trg_sync_reporting_to_profiles_manager
  AFTER INSERT OR UPDATE OR DELETE ON public.reporting
  FOR EACH ROW EXECUTE FUNCTION public.sync_reporting_to_profiles_manager();

DROP TRIGGER IF EXISTS trg_role_permissions_updated_at ON public.role_permissions;
CREATE TRIGGER trg_role_permissions_updated_at
  BEFORE UPDATE ON public.role_permissions
  FOR EACH ROW EXECUTE FUNCTION public.touch_role_permissions_updated_at();

DROP TRIGGER IF EXISTS trg_acknowledge_permission ON public.special_tasks;
CREATE TRIGGER trg_acknowledge_permission
  BEFORE UPDATE ON public.special_tasks
  FOR EACH ROW EXECUTE FUNCTION public.check_acknowledge_permission();

DROP TRIGGER IF EXISTS trg_enforce_special_task_updates ON public.special_tasks;
CREATE TRIGGER trg_enforce_special_task_updates
  BEFORE UPDATE ON public.special_tasks
  FOR EACH ROW EXECUTE FUNCTION public.enforce_special_task_updates();

DROP TRIGGER IF EXISTS trg_team_job_tasks_updated_at ON public.team_job_tasks;
CREATE TRIGGER trg_team_job_tasks_updated_at
  BEFORE UPDATE ON public.team_job_tasks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_team_jobs_updated_at ON public.team_jobs;
CREATE TRIGGER trg_team_jobs_updated_at
  BEFORE UPDATE ON public.team_jobs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── RPC functions used directly by the frontend ─────────────────────────────

CREATE OR REPLACE FUNCTION public.create_employee_full(
  p_name text, p_email text, p_phone_no text DEFAULT NULL, p_department text DEFAULT NULL,
  p_role text DEFAULT 'Executive', p_branch text DEFAULT NULL, p_reporting_to_id uuid DEFAULT NULL
)
 RETURNS uuid
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_user_id   UUID;
  v_pass      TEXT;
BEGIN
  IF auth_role() NOT IN ('managing_director', 'executive_assistant', 'hr') THEN
    RAISE EXCEPTION 'Not authorized to create employees';
  END IF;

  v_pass := COALESCE(NULLIF(TRIM(p_phone_no), ''), 'ChangeMe123!');

  INSERT INTO auth.users (
    id, instance_id, email, encrypted_password,
    email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at, role, aud,
    confirmation_token, recovery_token, email_change_token_new, email_change
  ) VALUES (
    gen_random_uuid(),
    '00000000-0000-0000-0000-000000000000',
    p_email,
    extensions.crypt(v_pass, extensions.gen_salt('bf')),
    NOW(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('full_name', p_name),
    NOW(), NOW(),
    'authenticated', 'authenticated',
    '', '', '', ''
  )
  RETURNING id INTO v_user_id;

  INSERT INTO auth.identities (
    id, user_id, provider_id, provider, identity_data,
    last_sign_in_at, created_at, updated_at
  ) VALUES (
    gen_random_uuid(), v_user_id, v_user_id, 'email',
    jsonb_build_object('sub', v_user_id::text, 'email', p_email),
    NOW(), NOW(), NOW()
  );

  UPDATE profiles SET
    email      = p_email,
    full_name  = p_name,
    phone_no   = p_phone_no,
    role       = CASE p_role
                   WHEN 'MD'       THEN 'managing_director'
                   WHEN 'Director' THEN 'director'
                   WHEN 'EA'       THEN 'executive_assistant'
                   WHEN 'HR'       THEN 'hr'
                   WHEN 'Manager'  THEN 'manager'
                   ELSE                 'executive'
                 END::user_role,
    branch     = p_branch,
    manager_id = p_reporting_to_id
  WHERE id = v_user_id;

  INSERT INTO profiles (id, email, full_name, phone_no, role, branch, manager_id)
  SELECT v_user_id, p_email, p_name, p_phone_no,
    CASE p_role
      WHEN 'MD'       THEN 'managing_director'
      WHEN 'Director' THEN 'director'
      WHEN 'EA'       THEN 'executive_assistant'
      WHEN 'HR'       THEN 'hr'
      WHEN 'Manager'  THEN 'manager'
      ELSE                 'executive'
    END::user_role,
    p_branch, p_reporting_to_id
  WHERE NOT EXISTS (SELECT 1 FROM profiles WHERE id = v_user_id);

  RETURN v_user_id;
END;
$function$;
REVOKE EXECUTE ON FUNCTION public.create_employee_full(text, text, text, text, text, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_employee_full(text, text, text, text, text, text, uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.delete_employee(p_employee_id uuid)
 RETURNS void
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid()
    AND role IN ('managing_director', 'director', 'executive_assistant')
  ) THEN
    RAISE EXCEPTION 'Insufficient permissions to delete employees.';
  END IF;

  IF p_employee_id = auth.uid() THEN
    RAISE EXCEPTION 'You cannot delete your own account.';
  END IF;

  DELETE FROM auth.users WHERE id = p_employee_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_employee_jd_report(p_employee_id uuid, p_start timestamptz, p_end timestamptz)
 RETURNS TABLE(id text, work_details text, monthly_target numeric, achieved_in_period numeric, status text)
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT can_view_employee(p_employee_id) THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    jd.id::TEXT,
    jd.work_details,
    jd.monthly_target::NUMERIC,
    COALESCE(agg.total, 0)::NUMERIC AS achieved_in_period,
    jd.status
  FROM job_directions jd
  LEFT JOIN (
    SELECT job_direction_id, SUM(amount_completed) AS total
    FROM job_direction_progress_logs
    WHERE employee_id = p_employee_id
      AND created_at >= p_start
      AND created_at <  p_end
    GROUP BY job_direction_id
  ) agg ON agg.job_direction_id = jd.id
  WHERE jd.employee_id = p_employee_id
  ORDER BY jd.work_details;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_employee_task_report(p_employee_id uuid, p_start timestamptz, p_end timestamptz)
 RETURNS TABLE(id text, task_name text, due_date date, status text, created_at timestamptz, completed_at timestamptz)
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT can_view_employee(p_employee_id) THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    st.id::TEXT,
    st.task_name,
    st.due_date,
    st.status,
    st.created_at,
    st.completed_at
  FROM special_tasks st
  JOIN task_assignees ta ON ta.task_id = st.id AND ta.employee_id = p_employee_id
  WHERE st.created_at >= p_start OR st.due_date >= p_start::DATE
  ORDER BY st.due_date DESC NULLS LAST, st.created_at DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_employee_team_task_report(p_employee_id uuid, p_start timestamptz, p_end timestamptz)
 RETURNS TABLE(id uuid, sub_task_title text, job_title text, task_type text, due_date date, status text, completed_at timestamptz, notes text, created_at timestamptz)
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT can_view_employee(p_employee_id) THEN
    RAISE EXCEPTION 'Access denied';
  END IF;

  RETURN QUERY
  SELECT
    t.id,
    t.title       AS sub_task_title,
    j.title       AS job_title,
    t.task_type,
    t.due_date,
    t.status::TEXT,
    t.completed_at,
    t.notes,
    t.created_at
  FROM  team_job_tasks t
  JOIN  team_jobs       j ON j.id = t.job_id
  WHERE t.assignee_id = p_employee_id
    AND t.created_at BETWEEN p_start AND p_end
  ORDER BY t.created_at DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_jd_monthly_history(p_year integer, p_month integer)
 RETURNS TABLE(id text, work_details text, monthly_target numeric, monthly_achieved numeric, employee_id uuid, employee_name text, status text)
 LANGUAGE plpgsql SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_caller_id   UUID := auth.uid();
  v_caller_role TEXT;
  v_start       TIMESTAMPTZ;
  v_end         TIMESTAMPTZ;
BEGIN
  SELECT role INTO v_caller_role FROM profiles WHERE id = v_caller_id;

  v_start := make_timestamptz(p_year, p_month, 1, 0, 0, 0, 'UTC');
  v_end   := v_start + INTERVAL '1 month';

  RETURN QUERY
  SELECT
    jd.id::TEXT,
    jd.work_details,
    jd.monthly_target,
    COALESCE(agg.total, 0)::NUMERIC AS monthly_achieved,
    jd.employee_id,
    p.full_name AS employee_name,
    jd.status
  FROM job_directions jd
  JOIN profiles p ON p.id = jd.employee_id
  LEFT JOIN (
    SELECT job_direction_id, SUM(amount_completed) AS total
    FROM job_direction_progress_logs
    WHERE created_at >= v_start AND created_at < v_end
    GROUP BY job_direction_id
  ) agg ON agg.job_direction_id = jd.id
  WHERE
    CASE
      WHEN v_caller_role IN ('managing_director', 'executive_assistant', 'hr', 'director')
        THEN TRUE
      WHEN v_caller_role = 'manager'
        THEN (jd.employee_id = v_caller_id OR jd.manager_id = v_caller_id)
      ELSE
        jd.employee_id = v_caller_id
    END
  ORDER BY p.full_name, jd.work_details;
END;
$function$;

-- ── View ────────────────────────────────────────────────────────────────────
-- security_invoker = true is required: without it, this view runs as its
-- owner and RLS on the underlying tables is never evaluated for the querying
-- user (see live-DB security fix applied 2026-07-01).
CREATE OR REPLACE VIEW public.job_directions_with_progress AS
SELECT
  jd.id,
  jd.work_details,
  jd.description,
  jd.expected_output,
  jd.expected_output_achieved,
  jd.employee_id,
  jd.manager_id,
  jd.department_id,
  jd.status,
  jd.remarks,
  jd.daily_target,
  jd.weekly_target,
  jd.monthly_target,
  COALESCE(daily.amount, 0::numeric) AS daily_completed,
  COALESCE(weekly.amount, 0::numeric) AS weekly_completed,
  COALESCE(monthly.amount, 0::numeric) AS monthly_completed
FROM job_directions jd
LEFT JOIN (
  SELECT job_direction_progress_logs.job_direction_id,
         sum(job_direction_progress_logs.amount_completed) AS amount
  FROM job_direction_progress_logs
  WHERE job_direction_progress_logs.created_at::date = CURRENT_DATE
  GROUP BY job_direction_progress_logs.job_direction_id
) daily ON daily.job_direction_id = jd.id
LEFT JOIN (
  SELECT job_direction_progress_logs.job_direction_id,
         sum(job_direction_progress_logs.amount_completed) AS amount
  FROM job_direction_progress_logs
  WHERE job_direction_progress_logs.created_at >= date_trunc('week', CURRENT_DATE::timestamp)
  GROUP BY job_direction_progress_logs.job_direction_id
) weekly ON weekly.job_direction_id = jd.id
LEFT JOIN (
  SELECT job_direction_progress_logs.job_direction_id,
         sum(job_direction_progress_logs.amount_completed) AS amount
  FROM job_direction_progress_logs
  WHERE job_direction_progress_logs.created_at >= date_trunc('month', CURRENT_DATE::timestamp)
  GROUP BY job_direction_progress_logs.job_direction_id
) monthly ON monthly.job_direction_id = jd.id;

ALTER VIEW public.job_directions_with_progress SET (security_invoker = true);

-- ── Row Level Security ──────────────────────────────────────────────────────

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_directions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_direction_progress_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.special_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reporting ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_schemas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_job_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.capacity_plans ENABLE ROW LEVEL SECURITY;

-- departments
DROP POLICY IF EXISTS "departments_read_all" ON public.departments;
CREATE POLICY "departments_read_all" ON public.departments FOR SELECT USING (true);
DROP POLICY IF EXISTS "departments_admin_write" ON public.departments;
CREATE POLICY "departments_admin_write" ON public.departments FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role]))
);

-- profiles
DROP POLICY IF EXISTS "profiles: all active read all active" ON public.profiles;
CREATE POLICY "profiles: all active read all active" ON public.profiles FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "profiles: self read" ON public.profiles;
CREATE POLICY "profiles: self read" ON public.profiles FOR SELECT USING (id = auth.uid());
DROP POLICY IF EXISTS "profiles: manager read reports" ON public.profiles;
CREATE POLICY "profiles: manager read reports" ON public.profiles FOR SELECT USING (manager_id = auth.uid());
DROP POLICY IF EXISTS "profiles: executive read all" ON public.profiles;
CREATE POLICY "profiles: executive read all" ON public.profiles FOR SELECT USING ((auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text]));
DROP POLICY IF EXISTS "profiles: dept head read dept" ON public.profiles;
CREATE POLICY "profiles: dept head read dept" ON public.profiles FOR SELECT USING (
  department_id = auth_dept_id() AND (auth_role())::text = ANY (ARRAY['director'::text, 'managing_director'::text, 'executive_assistant'::text, 'hr'::text])
);
DROP POLICY IF EXISTS "profiles: self update" ON public.profiles;
CREATE POLICY "profiles: self update" ON public.profiles FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid());
DROP POLICY IF EXISTS "profiles: admin update any" ON public.profiles;
CREATE POLICY "profiles: admin update any" ON public.profiles FOR UPDATE
  USING ((auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text, 'director'::text]))
  WITH CHECK ((auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text, 'director'::text]));

-- notifications
DROP POLICY IF EXISTS "notifications: own only" ON public.notifications;
CREATE POLICY "notifications: own only" ON public.notifications FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- job_directions
DROP POLICY IF EXISTS "job_directions: select scope" ON public.job_directions;
CREATE POLICY "job_directions: select scope" ON public.job_directions FOR SELECT USING (
  employee_id = auth.uid() OR manager_id = auth.uid() OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "job_directions: admin read all" ON public.job_directions;
CREATE POLICY "job_directions: admin read all" ON public.job_directions FOR SELECT USING (
  (auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text])
);
DROP POLICY IF EXISTS "job_directions: insert scope" ON public.job_directions;
CREATE POLICY "job_directions: insert scope" ON public.job_directions FOR INSERT WITH CHECK (
  employee_id = auth.uid() OR manager_id = auth.uid() OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "job_directions: update scope" ON public.job_directions;
CREATE POLICY "job_directions: update scope" ON public.job_directions FOR UPDATE USING (
  employee_id = auth.uid() OR manager_id = auth.uid() OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "job_directions: delete scope" ON public.job_directions;
CREATE POLICY "job_directions: delete scope" ON public.job_directions FOR DELETE USING (
  manager_id = auth.uid() OR (employee_id = auth.uid() AND status = 'draft'::text) OR
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['director'::user_role, 'managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role]))
);

-- job_direction_progress_logs
DROP POLICY IF EXISTS "Employees can read their own logs" ON public.job_direction_progress_logs;
CREATE POLICY "Employees can read their own logs" ON public.job_direction_progress_logs FOR SELECT USING (auth.uid() = employee_id);
DROP POLICY IF EXISTS "Employees can insert their own logs" ON public.job_direction_progress_logs;
CREATE POLICY "Employees can insert their own logs" ON public.job_direction_progress_logs FOR INSERT WITH CHECK (auth.uid() = employee_id);
DROP POLICY IF EXISTS "Managers can read team logs" ON public.job_direction_progress_logs;
CREATE POLICY "Managers can read team logs" ON public.job_direction_progress_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = job_direction_progress_logs.employee_id AND profiles.manager_id = auth.uid())
);
DROP POLICY IF EXISTS "Directors/MDs can read all logs" ON public.job_direction_progress_logs;
CREATE POLICY "Directors/MDs can read all logs" ON public.job_direction_progress_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['director'::user_role, 'managing_director'::user_role, 'executive_assistant'::user_role]))
);

-- special_tasks
DROP POLICY IF EXISTS "special_tasks: select scope" ON public.special_tasks;
CREATE POLICY "special_tasks: select scope" ON public.special_tasks FOR SELECT USING (
  assigned_by = auth.uid() OR is_task_assignee(id, auth.uid()) OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "special_tasks: admin read all" ON public.special_tasks;
CREATE POLICY "special_tasks: admin read all" ON public.special_tasks FOR SELECT USING (
  (auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text])
);
DROP POLICY IF EXISTS "special_tasks: manager full" ON public.special_tasks;
CREATE POLICY "special_tasks: manager full" ON public.special_tasks FOR ALL USING (
  assigned_by = auth.uid() OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "special_tasks: assignee update status" ON public.special_tasks;
CREATE POLICY "special_tasks: assignee update status" ON public.special_tasks FOR UPDATE
  USING (is_task_assignee(id, auth.uid())) WITH CHECK (is_task_assignee(id, auth.uid()));

-- task_assignees
DROP POLICY IF EXISTS "task_assignees: select" ON public.task_assignees;
CREATE POLICY "task_assignees: select" ON public.task_assignees FOR SELECT USING (
  employee_id = auth.uid() OR is_task_creator(task_id, auth.uid()) OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "task_assignees: insert" ON public.task_assignees;
CREATE POLICY "task_assignees: insert" ON public.task_assignees FOR INSERT WITH CHECK (
  is_task_creator(task_id, auth.uid()) OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);
DROP POLICY IF EXISTS "task_assignees: delete" ON public.task_assignees;
CREATE POLICY "task_assignees: delete" ON public.task_assignees FOR DELETE USING (
  is_task_creator(task_id, auth.uid()) OR auth_role() = ANY (ARRAY['director'::user_role, 'managing_director'::user_role])
);

-- reporting
DROP POLICY IF EXISTS "Anyone can view reporting relationships" ON public.reporting;
CREATE POLICY "Anyone can view reporting relationships" ON public.reporting FOR SELECT USING (auth.role() = 'authenticated'::text);
DROP POLICY IF EXISTS "MD, Director and EA can insert reporting" ON public.reporting;
CREATE POLICY "MD, Director and EA can insert reporting" ON public.reporting FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'director'::user_role, 'executive_assistant'::user_role]))
);
DROP POLICY IF EXISTS "MD, Director and EA can update reporting" ON public.reporting;
CREATE POLICY "MD, Director and EA can update reporting" ON public.reporting FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'director'::user_role, 'executive_assistant'::user_role]))
);
DROP POLICY IF EXISTS "MD, Director and EA can delete reporting" ON public.reporting;
CREATE POLICY "MD, Director and EA can delete reporting" ON public.reporting FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'director'::user_role, 'executive_assistant'::user_role]))
);

-- role_permissions
DROP POLICY IF EXISTS "role_permissions: public read" ON public.role_permissions;
CREATE POLICY "role_permissions: public read" ON public.role_permissions FOR SELECT USING (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "role_permissions: admin update" ON public.role_permissions;
CREATE POLICY "role_permissions: admin update" ON public.role_permissions FOR UPDATE
  USING ((auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text]))
  WITH CHECK ((auth_role())::text = ANY (ARRAY['managing_director'::text, 'executive_assistant'::text, 'hr'::text]));

-- branches
DROP POLICY IF EXISTS "branches_read_all" ON public.branches;
CREATE POLICY "branches_read_all" ON public.branches FOR SELECT USING (true);
DROP POLICY IF EXISTS "branches_admin_write" ON public.branches;
CREATE POLICY "branches_admin_write" ON public.branches FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role]))
);

-- ui_schemas
DROP POLICY IF EXISTS "ui_schemas_read_all" ON public.ui_schemas;
CREATE POLICY "ui_schemas_read_all" ON public.ui_schemas FOR SELECT USING (true);
DROP POLICY IF EXISTS "ui_schemas_admin_write" ON public.ui_schemas;
CREATE POLICY "ui_schemas_admin_write" ON public.ui_schemas FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role]))
);

-- team_jobs
DROP POLICY IF EXISTS "team_jobs_select" ON public.team_jobs;
CREATE POLICY "team_jobs_select" ON public.team_jobs FOR SELECT TO authenticated USING (
  is_team_job_member(id) OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role, 'director'::user_role])
);
DROP POLICY IF EXISTS "team_jobs_insert" ON public.team_jobs;
CREATE POLICY "team_jobs_insert" ON public.team_jobs FOR INSERT TO authenticated WITH CHECK (
  is_manager_or_above() AND created_by = auth.uid()
);
DROP POLICY IF EXISTS "team_jobs_update" ON public.team_jobs;
CREATE POLICY "team_jobs_update" ON public.team_jobs FOR UPDATE TO authenticated USING (
  created_by = auth.uid() OR head_id = auth.uid() OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role])
);
DROP POLICY IF EXISTS "team_jobs_delete" ON public.team_jobs;
CREATE POLICY "team_jobs_delete" ON public.team_jobs FOR DELETE TO authenticated USING (
  created_by = auth.uid() OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role])
);

-- team_job_tasks
DROP POLICY IF EXISTS "team_job_tasks_select" ON public.team_job_tasks;
CREATE POLICY "team_job_tasks_select" ON public.team_job_tasks FOR SELECT TO authenticated USING (
  is_team_job_member(job_id) OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role, 'director'::user_role])
);
DROP POLICY IF EXISTS "team_job_tasks_insert" ON public.team_job_tasks;
CREATE POLICY "team_job_tasks_insert" ON public.team_job_tasks FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM team_jobs WHERE team_jobs.id = team_job_tasks.job_id AND (team_jobs.created_by = auth.uid() OR team_jobs.head_id = auth.uid()))
  OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role])
);
DROP POLICY IF EXISTS "team_job_tasks_update" ON public.team_job_tasks;
CREATE POLICY "team_job_tasks_update" ON public.team_job_tasks FOR UPDATE TO authenticated USING (
  assignee_id = auth.uid()
  OR EXISTS (SELECT 1 FROM team_jobs WHERE team_jobs.id = team_job_tasks.job_id AND (team_jobs.created_by = auth.uid() OR team_jobs.head_id = auth.uid()))
  OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role])
);
DROP POLICY IF EXISTS "team_job_tasks_delete" ON public.team_job_tasks;
CREATE POLICY "team_job_tasks_delete" ON public.team_job_tasks FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM team_jobs WHERE team_jobs.id = team_job_tasks.job_id AND (team_jobs.created_by = auth.uid() OR team_jobs.head_id = auth.uid()))
  OR (SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role])
);

-- capacity_plans
DROP POLICY IF EXISTS "capacity_plans_read" ON public.capacity_plans;
CREATE POLICY "capacity_plans_read" ON public.capacity_plans FOR SELECT USING (auth.role() = 'authenticated'::text);
DROP POLICY IF EXISTS "capacity_plans_write_admin" ON public.capacity_plans;
CREATE POLICY "capacity_plans_write_admin" ON public.capacity_plans FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role]))
);
DROP POLICY IF EXISTS "capacity_plans_write_director" ON public.capacity_plans;
CREATE POLICY "capacity_plans_write_director" ON public.capacity_plans FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'director'::user_role AND profiles.branch = capacity_plans.branch)
);

-- ── Auth trigger (profile auto-creation on signup) ──────────────────────────
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
