-- ============================================================
-- Migration 046: Fix employee-add authorization and reporting-
-- table gaps that let assigned employees vanish from RBAC views
-- ============================================================

-- 1. create_employee_full had no server-side role check — the comment on
--    migration 018 explicitly says "the component's own RBAC guard controls
--    who can reach this", but the RPC is SECURITY DEFINER and GRANTed to
--    every authenticated user, so anyone could call it directly (e.g. via
--    devtools) and create themselves a managing_director account.
--    Restrict execution to MD / HR / EA, matching the front-end gate.
CREATE OR REPLACE FUNCTION public.create_employee_full(
  p_name          TEXT,
  p_email         TEXT,
  p_phone_no      TEXT     DEFAULT NULL,
  p_department    TEXT     DEFAULT NULL,
  p_role          TEXT     DEFAULT 'Executive',
  p_branch        TEXT     DEFAULT NULL,
  p_reporting_to_id UUID   DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id   UUID;
  v_pass      TEXT;
  v_caller_role TEXT;
BEGIN
  SELECT role::text INTO v_caller_role FROM public.profiles WHERE id = auth.uid();
  IF v_caller_role IS NULL OR v_caller_role NOT IN ('managing_director', 'hr', 'executive_assistant') THEN
    RAISE EXCEPTION 'Only MD, HR, and EA can add employees';
  END IF;

  v_pass := COALESCE(NULLIF(TRIM(p_phone_no), ''), 'ChangeMe123!');

  -- 1. Create the auth user via Supabase admin helpers
  --    (SECURITY DEFINER means this runs as the DB owner who has access to auth.users)
  INSERT INTO auth.users (
    id,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    role,
    aud
  )
  VALUES (
    gen_random_uuid(),
    p_email,
    -- bcrypt hash of the password (which is the phone number or ChangeMe123!)
    crypt(v_pass, gen_salt('bf')),
    NOW(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object('full_name', p_name),
    NOW(),
    NOW(),
    'authenticated',
    'authenticated'
  )
  RETURNING id INTO v_user_id;

  -- 2. Insert profile row (employee_code auto-generated by column default)
  INSERT INTO profiles (
    id,
    email,
    full_name,
    phone_no,
    role
  ) VALUES (
    v_user_id,
    p_email,
    p_name,
    p_phone_no,
    -- map reporting role text to user_role enum; default to 'executive'
    CASE p_role
      WHEN 'MD'       THEN 'managing_director'
      WHEN 'Director' THEN 'director'
      WHEN 'EA'       THEN 'executive_assistant'
      WHEN 'HR'       THEN 'hr'
      WHEN 'Manager'  THEN 'manager'
      ELSE                 'executive'
    END::user_role
  );

  -- 3. Insert reporting record if any reporting fields provided
  IF p_department IS NOT NULL OR p_branch IS NOT NULL THEN
    INSERT INTO reporting (
      employee_id,
      department,
      role,
      branch,
      reporting_to_id
    ) VALUES (
      v_user_id,
      COALESCE(p_department, ''),
      COALESCE(p_role, 'Executive'),
      COALESCE(p_branch, ''),
      p_reporting_to_id
    );
  END IF;

  RETURN v_user_id;
END;
$$;

-- 2. reporting-table RLS was missing 'hr' on insert/update/delete, even
--    though HR is allowed to add/edit employees in the UI. That silently
--    dropped the reporting-row write (while profiles.manager_id still
--    updated via the separate admin-update policy), leaving the assigned
--    employee invisible to their new manager's RBAC-filtered views.
DROP POLICY IF EXISTS "MD, Director and EA can insert reporting" ON public.reporting;
CREATE POLICY "MD, Director, EA and HR can insert reporting" ON public.reporting FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role]))
);
DROP POLICY IF EXISTS "MD, Director and EA can update reporting" ON public.reporting;
CREATE POLICY "MD, Director, EA and HR can update reporting" ON public.reporting FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role]))
);
DROP POLICY IF EXISTS "MD, Director and EA can delete reporting" ON public.reporting;
CREATE POLICY "MD, Director, EA and HR can delete reporting" ON public.reporting FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = ANY (ARRAY['managing_director'::user_role, 'director'::user_role, 'executive_assistant'::user_role, 'hr'::user_role]))
);

-- 3. reporting.role's CHECK constraint never included 'HR', even though the
--    UI's role dropdown offers it — any HR employee's reporting row insert
--    would fail its constraint outright.
ALTER TABLE public.reporting DROP CONSTRAINT IF EXISTS reporting_role_check;
ALTER TABLE public.reporting ADD CONSTRAINT reporting_role_check
  CHECK (role = ANY (ARRAY['MD', 'Director', 'EA', 'HR', 'Manager', 'Executive']));
